Remove the DiSCo agent
It turns out that the DiSCo agent and the Maven module aws-xray-recorder-sdk-aws-sdk-v2-instrumentor are two independent auto-instrumentation methods. When we have both, they fight, causing a 'java.lang.NoClassDefFoundError: software/amazon/awssdk/core/interceptor/ExecutionInterceptor'.

The DiSCo agent has a number of auto-instrumentation plugins (e.g. AWS, SQL) whereas the Maven module only auto-instruments AWS API calls.